image: gradle:7.2-jdk8

stages:
  - build
  - test
  - deploy

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cp gradle.properties.example gradle.properties

.build: &build
  stage: build
  script:
    - gradle --build-cache jar
    - ls ./build/libs
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

Tests:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

Build:
  <<: *build
  only:
    - master
    - tags
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 30 days

Build branch:
  <<: *build
  except:
    - master
    - tags
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 5 days

Artifactory distribution:
  stage: deploy
  only:
    - master
    - tags
  script:
    - 'sed -i '':a;N;$!ba;s/\(artifactory_user = \)[^\n]*/\1''"${ARTIFACTORY_USER}"''/g'' gradle.properties'
    - 'sed -i '':a;N;$!ba;s/\(artifactory_password = \)[^\n]*/\1''"${ARTIFACTORY_PASSWORD}"''/g'' gradle.properties'
    - gradle publish
